CREATE TABLE IF NOT EXISTS tracking_device (
    id SERIAL NOT NULL PRIMARY KEY,
    point public.geometry(Point,4326),
    heading integer NOT NULL,
    velocity integer NOT NULL,
    altitude integer NOT NULL,
    seen timestamp with time zone,
    deviceid character varying(128) NOT NULL,
    registration character varying(32) NOT NULL,
    symbol character varying(32) NOT NULL,
    district character varying(32) NOT NULL,
    message integer NOT NULL,
    contractor_details character varying(50),
    callsign character varying(50),
    current_driver character varying(50),
    usual_driver character varying(50),
    usual_location character varying(50),
    rin_number integer,
    other_details text,
    source_device_type character varying(32) NOT NULL,
    rin_display character varying(5),
    callsign_display character varying(50),
    district_display character varying(100) NOT NULL,
    internal_only boolean NOT NULL,
    hidden boolean NOT NULL,
    deleted boolean NOT NULL,
    fire_use boolean,
    fire_type boolean
);
CREATE TABLE IF NOT EXISTS tracking_loggedpoint (
    id SERIAL NOT NULL PRIMARY KEY,
    point public.geometry(Point,4326) NOT NULL,
    heading integer NOT NULL,
    velocity integer NOT NULL,
    altitude integer NOT NULL,
    seen timestamp with time zone NOT NULL,
    device_id integer NOT NULL,
    raw text,
    message integer NOT NULL,
    source_device_type character varying(32) NOT NULL
);
