apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -uat
resources:
  - ../../base
secretGenerator:
  - name: fleetcare-data-harvest-env
    type: Opaque
    envs:
    - .env
labels:
  - includeSelectors: true
    pairs:
      variant: uat
patches:
  - path: deployment_patch.yaml
