apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fleetcare-data-harvest-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: fleetcare-data-harvest-prod
      variant: prod
