apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetcare-data-harvest
spec:
  strategy:
    type: RollingUpdate
  replicas: 2
  template:
    spec:
      containers:
      - name: fleetcare-data-harvest
        image: ghcr.io/dbca-wa/fleetcare-data-harvest
        env:
          - name: TZ
            value: "Australia/Perth"
        resources:
          requests:
            memory: "64Mi"
            cpu: "5m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        startupProbe:
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 15
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 10
        securityContext:
          runAsNonRoot: true
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
          - mountPath: /tmp
            name: tmpfs-ram
      volumes:
        - name: tmpfs-ram
          emptyDir:
            medium: "Memory"
      restartPolicy: Always
      terminationGracePeriodSeconds: 180
