name: 'Run unit tests'

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5432/postgres
    services:
      postgres:
        image: postgis/postgis:15-3.4-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.13'
          enable-cache: true
      - name: Install dependencies
        run: uv sync
      - name: Run unit tests
        run: uv run pytest -v --dburl $DATABASE_URL
